name: CI/CD Pipeline Role
on:
  workflow_dispatch:


jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712877925:role/CodeDeployRole
          aws-region: us-east-1

      # Step 2: Create CodeDeploy Deployment
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          echo "Creating CodeDeploy deployment..."
          DEPLOYMENT_ID=$(aws deploy create-deployment \
                          --application-name IISStopApp \
                          --deployment-group-name IISGroup \
                          --deployment-config-name CodeDeployDefault.OneAtATime \
                          --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
                          --query "deploymentId" --output text)
          echo "Deployment created with ID: ${DEPLOYMENT_ID}"
          echo "::set-output name=deploymentId::${DEPLOYMENT_ID}"
