name: Param Reteieve cmd

on:
  workflow_dispatch: 
jobs:
    param_retrieve:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712877925:role/CodeDeployRole
          aws-region: us-east-1

      - name: Run sh
        run: dir
