name: Version Test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
     S3_PATH: s3://testwar-viky/Artifacts/
    steps:
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: arn:aws:iam::339712877925:role/CodeDeployRole
         role-session-name: Github-deployment
         aws-region: us-east-1
     - name: count file
       id: count_files
       run: |
          file_count=$(aws s3 ls $S3_PATH  | wc -l)
          file_count=$(($file_count - 1))
          echo "Number of files in S3 folder: $file_count"
          echo "CURRENT_PACKAGE=$file_count" >> $GITHUB_ENV
     - name: Upload to the Artifactory
       run: |
          echo $CURRENT_PACKAGE
          echo "Test" >> appspec.yml
          ls -ltrh
          echo  "aws s3 cp appspec.yml  s3://testwar-viky/Artifacts/App-${CURRENT_PACKAGE}.yml"
          aws s3 cp appspec.yml  s3://testwar-viky/Artifacts/App-${CURRENT_PACKAGE}.yml
          aws s3 rm s3://testwar-viky/Artifacts/latest/ --recursive
          aws s3 cp appspec.yml  s3://testwar-viky/Artifacts/latest/App-${CURRENT_PACKAGE}.yml
        
